import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="bg-gradient-to-tl from-pink-200 via-violet-200 to-blue-200 min-h-screen font-mono">
          <div className="flex-col text-xl font-mono">
              <div className="flex justify-center">
                <Sidebar/>
              </div>
          </div>
          <main className="pl-35 font-mono">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
